version: 2
updates:
    - package-ecosystem: "flutter"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "daily"
