name: itba_damm
description: "ITBA DAMM class examples"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  beamer: ^1.6.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_dotenv: ^5.1.0
  logger: ^2.4.0
  dio: ^5.7.0
  flutter_flavorizr: ^2.2.3
  equatable: ^2.0.5
  fpdart: ^1.1.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  husky: ^0.1.7
  commitlint_cli: ^0.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/riverpod/config/env/.env.development

flavorizr:
  flavors:
    development:
      app:
        name: "Riverpod Test"

      android:
        applicationId: "ar.edu.itba.damm.development.riverpodtest"
      ios:
        bundleId: "ar.edu.itba.damm.development.riverpodtest"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
